### ISSUE TITLE
Greyscale conversion of images only optional

### ISSUE THREAD

**Issue by WolfgangDpunkt** [hauke96/wiki2book#50]
I understand why the images do not need to be colourful for most current ebook readers and that a prior conversion contributes to better display.

However, there are already the first usefully usable standard colour screens (for example, the PocketBook Color).
I, for example, tend to read the short Wiki articles on my smartphone.

Therefore, it would be great if the greyscale conversion could be deactivated via command line parameters. Or it could be activated, depending on what seems to make more sense by default.

So far, I have helped myself by deleting this part in api.go: `"-colorspace", "gray", "-separate".`

But an option for the non-tech-savvy might be a good idea for the future

**Comment by hauke96** [comment]
This will definitely be made configurable sooner or later. I'll have to work on the image processing anyway due to #39 .

**Comment by hauke96** [comment]
Just implemented this. It'll be part of v0.2.

**Comment by WolfgangDpunkt** [comment]
Great, I will try it out soon! Thank you :-)
